### ISSUE TITLE
Support for Tags as keywords [feature request]

### ISSUE THREAD

**Issue by mm-tom** [khalwat/seomatic#10]
Hello!

On the blog I am looking to integrate this plugin with, we have a tag field associated with each entry that has pretty accurate tags, helping to link the article with other articles.

It would be quite useful if SEOmatic allowed assignment of a tag field as keyword source... It would need only to parse the tags in to a plain text version.

:heart:

**Comment by sg-modlab** [comment]
FWIW I believe you can populate the keywords with other data in template. To override defaults. We are doing this with a few meta elements.

**Comment by mm-tom** [comment]
Aha, right - I see that might be one way to achieve it, thanks!

I think this feature request is still valid however - having functionality within the CP is still useful.

**Comment by khalwat** [comment]
mm-tom, that's a cool idea, I like it.  I'll see what it'd take to support Tags fields as a source for Keywords in the SEOmatic Meta FieldType.

As @sg-modiab pointed out, you can do it already via Twig templating if you wish.

**Comment by khalwat** [comment]
@mm-tom I added the ability to pull from Tags fields now, just pushed it:

https://github.com/khalwat/seomatic

Note that what you _probably_ want is to select **From Field** as a source, which will give you all of the tags.  If you use **Keywords From Field** it'll only give you the tags that TextRank thinks are most important.  In your case, since you've already specified Tags, we can assume they are important enough that it should always grab all of them.

**Comment by mm-tom** [comment]
:+1:
