### ISSUE TITLE
Installation via composer not working

### ISSUE THREAD

**Issue by jackmcpickle** [khalwat/seomatic#123]
`$composer install`
outputs 

```
Loading composer repositories with package information
Updating dependencies (including require-dev)               
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for nystudio107/seomatic dev-master -> satisfiable by nystudio107/seomatic[dev-master].
    - nystudio107/seomatic dev-master requires crodas/text-rank dev-master -> satisfiable by crodas/text-rank[dev-master] but these conflict with your requirements or minimum-stability.
```

in my `composer.json` file

``` json
"require": {
  "nystudio107/seomatic": "dev-master"
}

```

**Comment by jackmcpickle** [comment]
seem to be able to get around it via add `"crodas/text-rank": "dev-master"` to my require object.
But not ideal.

**Comment by timkelty** [comment]
@jackmcpickle Unfortunately, since `crodas/text-rank` doesn't have proper versions published, you're on the right track.

I have:

```
    "nystudio107/seomatic": "^1.1.5",
    "crodas/text-rank": "@dev",
```

The only difference here is that the stability flag (`@`), flags just that one requirement, and allows you to still maintain`minimum-stability: stable` as your default.

**Comment by khalwat** [comment]
Thanks @timkelty
