### ISSUE TITLE
Missing entities

### ISSUE THREAD

**Issue by wfendler** [khalwat/seomatic#142]
I'm pretty new to structured data and all these different entity types so apologies if I'm totally missing something but I was wondering what determined the available entity types in SEOmatic?

I'm looking to set up some job postings and found that [JobPosting](https://schema.org/JobPosting) is an entity type that exists. Is there a reason some are missing or is this a misuse of SEOmatic's Entity field?

Also, major thanks for all the hard work on this. 💯

**Comment by khalwat** [comment]
Yeah so you're right that `JobPosting` is missing; you can see all of the ones that are included here:

https://github.com/nystudio107/seomatic/blob/master/resources/js/main_entity_type_list.js

I tried to pick things that would be useful from the relatively generic (title, description, url) information we have, so included there are:
- All `CreativeWork` types
- All  `Event` types
- All `Person` types
- All `Product` types

Some of the `Intangible` types (of which `JobPosting` is one) make sense to include; but a lot don't.  You can see all of the types here:

http://schema.org/docs/full.html

If I included every single schema, I think it might actually be less useful to the majority, because there would be an overwhelming list of things to churn through.  So I tried to pick the most common types, and provide all of _them_

There's nothing preventing you from changing the `type` of the `mainEntityOfPage` variable to whatever you want via Twig tho, including changing it to be a `JobPosting`:

https://github.com/nystudio107/seomatic/wiki/10.-Dynamic-Twig-SEO-Meta

&

https://github.com/nystudio107/seomatic/wiki/08.-Main-Entity-of-Page-Microdata

**Comment by wfendler** [comment]
Ahh got it. I assumed some were excluded because of that very reason – there are so many – but didn't think how to add them myself. I'll definitely do that.

Thanks for the quick reply!
