### ISSUE TITLE
Can't install via composer

### ISSUE THREAD

**Issue by mofman** [khalwat/seomatic#160]
When trying to install via composer I get this error 

`requires crodas/text-rank dev-master -> satisfiable by crodas/text-rank[dev-master] but these conflict with your requirements or minimum-stability.`

**Comment by timkelty** [comment]
@mofman because `crodas/text-rank` doesn't have real versions published, you need to also put something like this in your `composer.json`:

```
{
  "require": {
    "nystudio107/seomatic": "^1.1.5",
    "crodas/text-rank": "@dev",
  },
}
```

The `@dev` tells composer to waive set `minimum-stability`, just for that dep.
Alternatively, you could set `minimum-stability: dev` globally, but you probably don't want to do that.

**Comment by timkelty** [comment]
Since it doesn't look like `crodas/text-rank` is maybe [ever going to get updated](https://github.com/crodas/TextRank/issues/3), it might make sense for @khalwat to just bake the dep into the plugin, not using Composer.
