### ISSUE TITLE
Hiding fields on entry edit page

### ISSUE THREAD

**Issue by frankharrison-wj** [khalwat/seomatic#163]
I've just started playing with this and looks great – super powerful and flexible. The one big request I'd have though is to be able to hide fields from content editors. For example:

- The "Main Entity of Page" would often be the same for any entry using a certain template, so I'd rather set that on a template level and hide from SEO Entry Meta
- We probably won't use "SEO Keywords", would be nice to be able to hide that too
- We'll always use the same image transform for Facebook and the same image transform for Twitter, so would be good to hide those options from SEO Entry Meta
- We'll always use the same image for SEO Image, Twitter Card Image and Facebook OpenGraph Image – so would be great to be able to just display the SEO Image field when editing an entry and have the others use that.

Doing this would make the SEO Entry Meta a lot less intimidating for clients – it would halve the amount of stuff they need to digest.

But thanks for the amazing (and free) plugin!

**Comment by khalwat** [comment]
So what you should do is set the defaults that you want for various things such as the image transforms, etc. in the Field Settings.  And then you can configure it so that various things can't be changed.  You could set the SEO Keywords to always extract keywords from a `blogBody` field (or whatever) and then set it such that it can't be changed when a content editor is editing it.

This is all available in the Field Settings.

**Comment by frankharrison-wj** [comment]
Thanks for replying, but I would still make a feature request:

When I set Default SEO Keywords to be from a field, and set SEO Keywords Source Changeable OFF, I still get a custom text input for SEO Keywords on the publish page. (Possibly a bug rather than by design?)

I've also got default image transforms etc set up in the custom field, but they still display in the publish page as options – I don't see a way to not display those drop-downs.

And finally, setting Twitter Card Image Source Changeable to OFF, it still displays the image for Twitter on the publish page – it's just not editable. Same goes for Facebook images. This isn't ideal, is I'd like my client to just have the option of changing the SEO image, and use that for both Twitter and FB. (I guess that might be possible as it is, but the interface wouldn't be very intuitive as the Twitter and FB images don't change when you change the SEO image)

Ideally, on the publish page, I would like to:

– hide the Main Entity of Page field
– hide the Keywords field
– hide the SEO Image Transform field
– hide all Twitter/Facebook image fields completely

I think this would make the publishing experience a lot clearer – my client would just see three fields (SEO Title, SEO Description and SEO Image) and the system would do the rest.

Hope that makes sense – happy to give you CP access to this site if it helps to see how I've got things set up.

**Comment by khalwat** [comment]
It sounds like you didn't re-save your section after adding the SEOmatic FieldType to it.  You need to do that as per the docs, otherwise the fields have no data in them to tell them what to default to:

https://github.com/nystudio107/seomatic/wiki/05.-SEO-Entry-Meta

> If you add an SEOmatic FieldType to an existing Section that already has entries in it, you'll need to re-save the Section to populate the newly added SEOmatic FieldType with data. You can do this via Settings → Edit My Section → hit Save.

I'm probably not going to make it so certain fields are selectively hide-able for this 1.x branch of the plugin.  I like the idea of showing information, but not having it editable, over actually hiding it.
