### ISSUE TITLE
Field for analytics ID?

### ISSUE THREAD

**Issue by timkelty** [khalwat/seomatic#19]
Current we keep our google analytics ID in globals. Was thinking it might be nice to have it within SEOmatic...thoughts?

**Comment by khalwat** [comment]
I was actually just mulling this over last night, in terms of whether it should be included in SEOmatic or not.

I think it's close, from the POV that it's not entirely related to SEO, but it's still something semi-related that maybe could be stuck in there.

If I did it, it would be that you pasted the whole script tag in though, I think, not just the ID... because sometimes you want customize things in the script, and Google does change it from time to time as well.

For instance, if you want `Enable Demographics and Interest Reports` you need to ad a line of code to the script tag:

https://support.google.com/analytics/answer/2444872?hl=en&utm_id=ad#trackingcode

I'm open to a discussion on whether it should be included, and how to handle it!

**Comment by timkelty** [comment]
Yeah I was on the fence whether it belonged, but I think it would be convenient for sure.

Dumping the whole script tag would probably be best for most people. In our case - we actually use the ID directly sometimes and build our own script.

But in that case, it wouldn't really matter - we could still use the field, only put our ID in, and just override the template to not dump the script tag and do whatever we wanted with it.

**Comment by sg-modlab** [comment]
I see this as feature bloat FWIW.

There's Analytics, Tag Manager, Piwik and they change ... put under body,
in head, before close yada yada ... then you don't want them in this
environment or that. You don't want them in live preview ....

Just cause SEO lives in head doesn't mean this plugin should also manage
stylesheets, scripts, analytics, ...

So easy to be done with a global or environment variable, too.

Again. just my $.02

On Wed, Feb 3, 2016 at 12:05 PM, Tim Kelty notifications@github.com wrote:

> Yeah I was on the fence whether it belonged, but I think it would be
> convenient for sure.
> 
> Dumping the whole script tag would probably be best for most people. In
> our case - we actually use the ID directly sometimes and build our own
> script.
> 
> But in that case, it wouldn't really matter - we could still use the
> field, only put our ID in, and just override the template to not dump the
> script tag and do whatever we wanted with it.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/nystudio107/seomatic/issues/19#issuecomment-179349133
> .

## 

seth giammanco
seth@mod-lab.com
ph 718.858.1066

minds on design lab
www.mod-lab.com
Subscribe to our Mailing List
https://confirmsubscription.com/h/y/12431274F3870FEA

**Comment by khalwat** [comment]
So I've vacillated back and forth on it for a while.  Part of me wanted it in there so I didn't need a Twig template for it; part of me found no good place for it to fit into the SEOmatic settings, which made me think that maybe it was a bit of as @sg-modlab termed it, feature bloat.

I think some of the changes I have coming for 1.1.0 are a bit more useful for the core SEO functionality, and I wonder if something like an integrated sitemap wouldn't be more useful from the POV of it being an total SEO solution out of the box.

**Comment by sg-modlab** [comment]
Sitemap makes sense to me.

**Comment by lindseydiloreto** [comment]
+1 for including the GA script. I'd love to just enter our code into the SEOmatic settings and be done with it.

Adding a sitemap makes a lot of sense to me as well, although Ben Croker already pretty much nailed it with his [Sitemap](https://craftpl.us/plugins/sitemap) plugin.

**Comment by timkelty** [comment]
I could go either way - but I'm leaning towards it being feature bloat.

What if the setting were merely labelled: **Additional content for seomaticRender hook**?
Then you could put whatever in there, GA script or not. No assumptions about where or what it does.

**Comment by khalwat** [comment]
So I discussed this on http://craftcms.slack.com with @lindseydiloreto and I think we came to a consensus that I tend to agree with:

People who want the quick and easy solution can just paste the Google Analytics UID into a field, and SEOmatic will do the right thing.

For people who don't want it, or have custom modifications to the GA script for adding additional features, or they want to control where it goes or whatever, they can just leave it blank.

Basically, make it super easy and simple for people who want that.  For people who want it custom, just leave the field blank and keep doing it your way.

The reasoning is basically this: the field is a convenience that is more than fine for the majority of sites; and if you want to do something special, no problem, just leave the field blank (just like with the Google Verification Code).  Realistically, Google doesn't really update the script portion at all, it's just a simple loader for the actual GA code.

I'll do it the right way, via a variable that's included in the `_seo_meta` template, and so on.  Also it will do smart things, like not include the GA code if you're running in `devMode` and so on.

**Comment by sg-modlab** [comment]
Thanks for sharing ... Goes down a path I think too many plugins go where they lose focus and simplicity because of addressing too many needs; however simple or ignorable they may seem.

Can I load my CSS, favicons, scripts and anything else that seems like meta because it may go into the head? Guess we'll see those in a future release ;-)

I enjoy being a part of the conversation and hope my contributions are seen as nothing but that.

Best

**Comment by timkelty** [comment]
> Realistically, Google doesn't really update the script portion at all

While this may be true, this seems like a nightmare in terms of support.

**Comment by khalwat** [comment]
> While this may be true, this seems like a nightmare in terms of support

Well, there are two ways to think about it.  The vast, vast majority of websites will never update their GA code at all.  Ever.  Most sites are created, paid for by the client, and away they go.

So I don't really see it as any worse of a support nightmare than already exists.  It might actually be better, because I'm more likely to update the GA code than most. :)

**Comment by lindseydiloreto** [comment]
According to hypothetical statistics I'm completely making up, it seems far more likely that:
1. @khalwat would update the GA implementation in SEOmatic.
2. A dev would update the SEOmatic plugin.

... rather than:
1. A dev re-implements the GA code just to get the latest format.

To me, it seems like a fairly small feature which would actually be helpful to a lot of people. And as a small feature, it doesn't tread very heavily into feature bloat territory.

Just speculating, of course. :)

**Comment by khalwat** [comment]
And away we go... 
![safariscreensnapz207](https://cloud.githubusercontent.com/assets/7570798/12837294/28fe3a66-cb8f-11e5-910a-4067f4a2dcba.png)
![safariscreensnapz211](https://cloud.githubusercontent.com/assets/7570798/12837297/2ebf76c2-cb8f-11e5-9848-536639afde3e.png)

**Comment by jasonmccallister** [comment]
This is great to add this, but the ability to append extra to the analytics tag is critical. For example, we would need commerce on several projects. 

To be fair, love this implementation. I just would like to be able to add GA specific code as well.

**Comment by khalwat** [comment]
@themccallister I got yer back:

![safariscreensnapz213](https://cloud.githubusercontent.com/assets/7570798/12870768/fd165d54-cd21-11e5-8a1d-1cff7cb58a19.png)

![safariscreensnapz214](https://cloud.githubusercontent.com/assets/7570798/12870769/046c88e4-cd22-11e5-9dcc-3882a6a8dbfc.png)

In addition to turning on whatever Google Analytics plugins you need, you can also control whether it automatically sends a PageView or not.

**Comment by khalwat** [comment]
Implemented in 1.1.0, which is now released.
