### ISSUE TITLE
SeomaticService.php

### ISSUE THREAD

**Issue by dorothyDorothy** [khalwat/seomatic#200]
Hi,
Can you add 
`$htmlText = '';`
to line 440 of SeomaticService.php please?

I've added it into my copy, thought that it would be good to share this with you.  It fixes a small bug which spawns the

> $htmlText is not defined

message
Cheers,
Dorothy

**Comment by khalwat** [comment]
Is this happening when you have an error in your Humans.txt template or such?

**Comment by khalwat** [comment]
I did it one better, and just do more effective error logging/reporting. So now if you make an error in one of your templates, it'll display what it is (as well as log it) instead of encountering the error you did.

Grab the build from `develop` to give it a whirl: https://github.com/nystudio107/seomatic/tree/develop

**Comment by dorothyDorothy** [comment]
Hi khalwat,
I was just filling in one of the set up screens, hadn't got as far as the templates yet.
Thanks for the swift fix.
;-)

**Comment by dorothyDorothy** [comment]
Nice plug-in by the way!
