### ISSUE TITLE
SEOmetrics not working. Error parsing the DOM.

### ISSUE THREAD

**Issue by jayhlee** [khalwat/seomatic#207]
SEOmetrics doesn't seem to work on my staging site. I get "Error parsing the DOM. Is this a valid, publicly accessible URL?". I have a local version of the exact same site and SEOmetrics works fine, so I'm not sure what's going on. Staging site has SSL/HTTP2, but I'm figuring that's not an issue?

**Comment by khalwat** [comment]
Is there a public URL you can give me that I can test against?

**Comment by jayhlee** [comment]
@khalwat Yes. The site's staged at eclectiv.net.

**Comment by khalwat** [comment]
It seems to work for me?

<img width="1040" alt="google chromescreensnapz248" src="https://cloud.githubusercontent.com/assets/7570798/23728300/194eb90e-042a-11e7-9be5-acbc68bd1158.png">

Perhaps something isn't configured right with your server? Is `curl` properly installed, etc.?

**Comment by jayhlee** [comment]
@khalwat I'm figuring it has to do with the server then. SEOmetrics doesn't seem to work on server setup by ServerPilot, although I'm not sure what's causing the issue. (Just checked and curl is installed with my ServerPilot set up.) SEOmetrics works on the exact website on my local version. I also put the site up on another LAMP server I configured myself and SEOmetrics works fine there as well. Any idea what the issue may be with how ServerPilot configures their setup?

**Comment by khalwat** [comment]
Can you try turning `devMode` on to see if any errors are displayed or logged in `seomatic.log` or `craft.log` when you try to do SEOmetrics?

**Comment by khalwat** [comment]
I'm reasonably certain that a number of people are using SEOmetrics successfully on a ServerPilot setup, but if not, we'll get it worked out.

**Comment by khalwat** [comment]
When you see that error message, this is what's failing, for whatever reason:

https://github.com/nystudio107/seomatic/blob/master/controllers/SeomaticController.php#L61

It's a third-party library I use to parse the DOM.

**Comment by matthew-rotter** [comment]
We're having the same problem on powweb, a custom setup and a hostgator account. 

All our ICDSoft setups are working fine, though ¯\_(ツ)_/¯

**Comment by khalwat** [comment]
Good luck with HostGator, I've had no end of trouble with them.

https://nystudio107.com/blog/web-hosting-for-agencies-freelancers

**Comment by jayhlee** [comment]
@khalwat It looks like it's a 404 error on a JS script. I'm not sure why it's doing this, though. 
<img width="880" alt="error" src="https://cloud.githubusercontent.com/assets/25807445/23821442/455e17ce-05e7-11e7-9363-b336f538abdf.png">

**Comment by bob3s** [comment]
I have the exact same issue. I think the issue is exactly as stated above. The plugin is referencing an older version of jquery while the newest edition of craft uses a later version (jquery-2.2.4). I have tried a couple of things like editing the references or adding an older version of jquery, but the error remains. Any ideas what could fix this issue?

**Comment by khalwat** [comment]
Very interesting, I'll see what I can find. I'm not even sure why it's asking for jQuery at all...

But it doesn't make sense to me that failing to load it would be an issue, especially if the Craft AdminCP is already loading a more recent version.

It seems to me that something else might be going on here too

**Comment by khalwat** [comment]
So this ends up being a fun one. As it turns out, the issue is that the HTMLSimpleDOM lib that SEOmatic uses end up calling `file_get_contents` to get the contents of the DOM to parse. One of the parameters this lib passes in by default is:

```
$offset = -1
```

After checking out the [PHP docs on file_get_contents](http://php.net/manual/en/function.file-get-contents.php), lo and behold:

```
Version	Description
7.1.0	Support for negative offsets has been added.
````

So this addition of supporting negative offsets causes the code to no longer work. I'm guessing everyone who is reporting this issue is running on PHP 7.1?

Anyway, changing it to just be:

```
$offset = 0
```

Fixes it in my test-case. I'll look into the jQuery issue as well, but I think it's a red herring.

**Comment by khalwat** [comment]
Alright, try the build in `develop`, it should do the trick:

https://github.com/nystudio107/seomatic/tree/develop

**Comment by khalwat** [comment]
btw, you were right @jayhlee that I was including the wrong jQuery... I've since moved it into the SEOmatic package so it won't break in the future when Craft updates their version.

But it was unrelated to this DOM parsing issue.

**Comment by jayhlee** [comment]
@khalwat Just installed the build in develop and everything now works swimmingly. Thanks for taking the time to look into this! Much appreciated!

**Comment by khalwat** [comment]
yay! Thanks for letting me know @jayhlee

**Comment by cavidano** [comment]
This issue is happening to me. My host provider (Liquidweb) has confirmed that I am up to date with PHP and have XML enabled. SEOmatic breaks my admin pages as well, meaning I cannot update entries that have the SEOmatic custom field. At this point, my only option is to uninstall SEOMatic completely. On my local server, everything works great.

![screencapture-avidanodigital-kirsty-seomatic-seometrics-1493900050206](https://cloud.githubusercontent.com/assets/3001196/25703586/294b7e04-30a4-11e7-883d-fb9629bceb61.png)

**Comment by khalwat** [comment]
@cavidano If it works locally, it's very likely something to do with your hosting. Again, have a read:

https://nystudio107.com/blog/web-hosting-for-agencies-freelancers

This is why I recommend _against_ boutique hosting like LiquidWeb
