### ISSUE TITLE
Feature Request - Humans File Auto include all plugins

### ISSUE THREAD

**Issue by terryupton** [khalwat/seomatic#214]
I always create a humans file for every project, even before using SEOMatic. As part of this I like to reference any support, plugins, code or modules I have used or have helped me with a particular project. I was thinking that this might be a useful feature (or if in fact there is already some code that could be dropped in to the humans file to do this) that would loop through all Craft Plugins that are installed and active and pull them into the humans file, as to not manually enter these for each one. I noticed that as part of the default file there are references to SEOMatic which is great and got me thinking about this -  but if it could be extended to include all plugins? 

Thoughts?

**Comment by khalwat** [comment]
It's a cool idea, but probably not something I'm going to do... because then the question is, okay, when do we scan for what plugins are used?

- When SEOmatic is first installed? What happens with plugins they add later (which is very common in projects)
- On every request? This would add overhead for something that's not really needed

How do we handle meshing the automatically generated list with hand-done changes to the humans.txt?

It just ends up being a pretty complicated problem to solve well.

FWIW, right now what it ends up using is the file: `seomatic/templates/_humansDefault.twig` -- you can make your own version of this, and copy it into that directory for each new project, and it'll use it for creating the default `humans.txt`, if that helps you.

**Comment by terryupton** [comment]
Thanks for considering Andrew. These are fair comments, and not something I had considered when initially raising the request.
