### ISSUE TITLE
Suggestion: Truncate description on last word

### ISSUE THREAD

**Issue by tomkiss** [khalwat/seomatic#227]
In the process of integrating SEOmatic in to a site I'm working on.

Our existing SEO solution has a function to truncate text, similar to SEOmatic. One thing that is nice though, is to truncate on a sentence (ending in . or !), if one appears in < 170 characters.

Something like:
```
  public function truncateDescription($desc) {
    // Use truncated entry text:
    // strip html tags, strip new lines, substr to 170 chars
    $desc = trim(preg_replace('/\s+/', ' ', strip_tags($desc)));
    $desc = substr($desc, 0, 170);
    // If period or exclamation found, substr to that, ignore short strings
    $posP = strrpos($desc, '.');
    $posE = strrpos($desc, '!');
    $pos = ($posP > $posE ? $posP : $posE);
    if(!empty($pos) && $pos > 30) {
      $desc = substr($desc, 0, $pos+1);
    }
    return $desc;
  }
```

This may not be desirable for everyone but it's worked well for us.

Results in this:

_Darth Vader, also known by his birth name Anakin Skywalker, is a fictional character in the Star Wars franchise._

Rather than this:

_Darth Vader, also known by his birth name Anakin Skywalker, is a fictional character in the Star Wars franchise. Vader appears in the original film trilogy as a pivotal_

**Comment by khalwat** [comment]
So the important thing to keep in mind is that it's a bot, not a person that is parsing the SEO description. As such, it's less important that sentence structure is intact, and more important that the keywords are there.

What it _really_ boils down to, though, is that people who create the SEO description craft it specifically for the SEO description field, and naturally have the sentences end properly.

That's not always the case, so then we fall back on automated truncating of the SEO description, and as per the above, I think it's probably better to do it on the word level rather than the sentence level.

**Comment by ellierider** [comment]
Just to add some color here. When those descriptions are then meant to be translated by an external service, it does poorly when the full sentence is not available.

**Comment by khalwat** [comment]
@ellierider that's a good use-case. You can increase the length that SEOmatic will truncate at to whatever you like in the Plugin settings
