### ISSUE TITLE
Server root, not site url being referenced on social media images.

### ISSUE THREAD

**Issue by atomworks** [khalwat/seomatic#238]
This is similar to #187 but I can't find anything to make me think it's a mistake on my end (though that doesn't mean it isn't, naturally).

The craft is running from a subfolder install on the domain ( /resources ), and though most of the data feeds through correctly, the images aren't.

See: https://hardwaremassive.com/resources/podcasts/episode-10-scaling-at-the-manufacturing-level

I had a quick look at the code and though I'm a bit out of my depth it looks like somewhere in the SeomaticService.php getFullyQualifiedUrl() function perhaps?

Either way, I've checked my asset folder paths, for this example the references are set to "images/" which works correctly on everything front end. The site url is set correctly in the config, I've tried updating it in the config.php file and even added the siteUrlOverride to see if that will make a difference but no luck.

Is this a bug or am I doing something stupid?

**Comment by khalwat** [comment]
Did you ever get this sorted?

**Comment by atomworks** [comment]
I didn't. I've been around in circles a few times trying to check if it's something I've done wrong. I've checked my settings, re-indexed, etc. but no luck. 

I took at the code again briefly but I got a little lost.

**Comment by khalwat** [comment]
Unfortunately, I need more info to attempt to fix this one :/

**Comment by atomworks** [comment]
What info do you need me to provide? Is this not something you can easily replicate by simply placing an install in a subfolder on a domain?

**Comment by khalwat** [comment]
So all the `getFullyQualifiedUrl()` function does is it takes whatever the `siteUrl` is and prepends it to the URL if it isn't a fully qualified URL.

In this case, what exactly is your `siteUrl` set to? Is it possible that the use of relative paths for your images is causing an issue?

From the URL you pasted in, it looks like the `og:image` ends up being:

https://hardwaremassive.com/images/featured/_featured/sink-or-sell.jpeg

...when I'm assuming it should be:

https://hardwaremassive.com/resources/images/featured/_featured/sink-or-sell.jpeg

This again makes me wonder if this is due to relative URLs being used.
