### ISSUE TITLE
truncateStringOnWord sometimes omits the ellipsis. 

### ISSUE THREAD

**Issue by terryupton** [khalwat/seomatic#242]
I have found when using truncateStringOnWord that it sometimes omits the ellipsis  even when the string is over the set characters. I cannot pinpoint this any more accurately but I think it might be when the next word is less than 3 characters. For example, on this statement;

"Specifiers are always looking for third party approval of products and there is no higher level of approval than the BASEC mark." I have set it to truncateStringOnWord at 80. This then truncates like so;
"Specifiers are always looking for third party approval of products and there is" without the ellipsis.

**Comment by khalwat** [comment]
So what it does is it truncates it to the specified limit, and if the resulting string is *exactly* at the limit, then it doesn't add the ellipsis. Otherwise it does.

I'm not sure if this is the best way to do it or not, but it feels wrong to truncate things further just to add our ellipsis. But then it also feels wrong to add the ellipsis so that it goes over the number of characters you said you wanted it to be.

Perhaps the answer is to truncate it to 1 less than what you ask for, and then always add the ellipsis?
