### ISSUE TITLE
Dynamic Twig SEO Meta is having no affect on json-ld

### ISSUE THREAD

**Issue by john-henry** [khalwat/seomatic#273]
If I add some dynamic twig SEO Meta. Take this for example

`{% set seomaticMeta = seomaticMeta | merge({'seoTitle': 'My Title' }) %}`

It will update the general meta like og twitter etc but does **_not_** affect json-ld.

With the above code the **name** and **headline** of `"@type": "NewsArticle"` only fallback to Site SEO Title and not the merged title.

**Comment by khalwat** [comment]
Just so I can make sure I'm understanding the question, this is MainEntityOfPage information coming from an Entry that has an SEOmatic FieldType attached to it yes?

**Comment by john-henry** [comment]
@khalwat correct

**Comment by john-henry** [comment]
Hi @khalwat Were you able to replicate this in any way?

**Comment by khalwat** [comment]
Right, so this is "expected behavior", in that the MainEntityOfPage information is pre-generated for each item, and typically isn't something you'd want to have change when you are making changes to the `seoTitle`

If you want to change it, you'll have to make the changes to the `seomaticMainEntityOfPage` array: https://github.com/nystudio107/seomatic/wiki/05.-SEO-Entry-Meta

```Main Entity of Page - The Main Entity of Page is a more specific, additional type that describes this entry. This additional JSON-LD structured data entity will be added to your page, more specifically describing the page's content. It is accessible via the seomaticMainEntityOfPage Twig variable, should you wish to modify or add to it.```
