### ISSUE TITLE
Tag Manager script gets rendered although devMode is enabled

### ISSUE THREAD

**Issue by klick** [khalwat/seomatic#280]
As said in the Title the Google Tag Manager script gets rendered inside the `<head>` although devMode is enabled thus messing up our data.

Is there something I am missing?

M

**Comment by khalwat** [comment]
There is a `renderGoogleTagManagerScript` variable you can leverage in the `config.php` to control this in a multi-environment way:

https://github.com/nystudio107/seomatic/blob/master/config.php

https://nystudio107.com/blog/prevent-google-from-indexing-staging-sites

The reason it doesn't automatically not render the GTM script if `devMode` is on is because GTM could be used to load pretty much anything, and potentially you might want it to be active in local dev.

Google Analytics, on the other hand, is never rendered if `devMode` is on.

**Comment by klick** [comment]
Alright, makes sense. Thank you!
