### ISSUE TITLE
Feature Update Request - Meta Title Length

### ISSUE THREAD

**Issue by snyderonlinemarketing** [khalwat/seomatic#286]
Currently, the SEOMatic plugin limits the meta title to 70 characters. 

Per `[this wiki](https://github.com/nystudio107/seomatic/wiki/10.-Dynamic-Twig-SEO-Meta)`: 

> Some of the seomaticMeta variables have character limitations on them, because search engines want to see only the most relevant, succinct information, and will truncate them during processing:
> 
> - seomaticMeta.seoTitle - 70 characters
> - seomaticMeta.seoDescription - 160 characters
> - seomaticMeta.seoKeywords - 200 characters
> 
> SEOmatic will automatically truncate these variables for you when you set them, so you don't have to worry about the length. It intelligently truncates them on whole-word boundaries, so nothing will get cut off.

In the past 6 months, Google has expanded its meta title length to 600 pixels (not 70 characters). The plugin currently auto-truncates meta titles longer than 70 characters even though they meet Google's current quality standards. Can an update occur where the meta title length is based on pixel width - or at least not truncate since Google will automatically do this anyway?

**Comment by khalwat** [comment]
If you want it to not truncate, you can do that via the `config.php` ->

https://github.com/nystudio107/seomatic/blob/master/config.php#L24

In any event, according to this article: http://www.thesempost.com/new-title-description-lengths-for-google-seo/

> The new title length is 70 characters before Google will truncate the title with ellipses (…).  This is an increase of 10-15 characters, which is pretty significant.  It can go up to at least 71 characters, depending on the letters used, since l and i are small characters.

So 70 characters still seems like a safe truncation width. While you could turn it off and allow Google to truncate it for you, it's probably better to manually make sure it fits, so that the title includes the important bits, imo

**Comment by snyderonlinemarketing** [comment]
thanks
