### ISSUE TITLE
Field defaults can't be changed onced saved

### ISSUE THREAD

**Issue by timkelty** [khalwat/seomatic#293]
Field defaults are only really only applicable when entries haven't been saved at all, which is unfortunate.

Example:

- You have an SEOmatic field and set the default SEO image field to something (e.g. a From Field → `myLogoField`).
- Later, you decide you want to set the default to something else, and you change the field defaults to From Field → `someNewImageField`.
- New entries are now saved with the new default, but old entries still use `myLogoField`.

The problem is that even though a user may not be touching the SEOmatic field at all, the act of saving an entry saves it with the default content at that time. From that point on it is impossible to tell what is actual saved data and what is default saved data.

Not sure what the right answer is…perhaps the **source** dropdowns could have a "Default" value?

/cc @robmcfadden let me know if I missed anything

**Comment by khalwat** [comment]
So by design (not saying it's ideal, just that's how it's done), the field settings in SEOmatic are meant to be defaults. They aren't meant to be something that you change, and then it goes in and globally changes all instances of the FieldType.

There are situations where that type of behavior would be bad; maybe the client has entered a bunch of custom data for the SEOmatic `seoTitle` for instance. If you changed it to default to pulling from a particular field, and it re-saved everything, it would blow away their custom settings.

So conceptually, we need to think about what these things are. I consider them defaults, which are used when a new entry is created, not something that can make global changes to the user's data.

I realize that this can be somewhat inconvenient. One way around it if you need to make global changes is you can delete the SEOmatic FieldType, and then re-add it with the new settings (it can even have the same name). All of the data in it will then default when you re-save that section.
