### ISSUE TITLE
Overriding seomatic.meta.robots value has no effect on <meta> tag (in production environment)

### ISSUE THREAD

**Issue by fthues** [khalwat/seomatic#390]
I'm conditionally setting seomatic.meta.robots to `none` like so whenever a certain query variable is set:

```
  {% if craft.app.request.getQueryParam('r') %}
    {% do seomatic.meta.robots('none') %}
  {% endif %}
```

I know the condition is working because the HTTP header `x-robots-tag` does change (from `all` to `none`).  However, the generated meta tag stays the same:

```
<meta name="robots" content="all">
```

I'm not doing anything out of the ordinary configuration wise.

**Comment by kennethormandy** [comment]
For anyone else that comes across this, it turned out to work as expected for me in production mode. Then, this worked:

```twig
{% do seomatic.meta.setAttributes({ robots: 'none' }) %}
```

…and this also worked:

```twig
{% do seomatic.meta.robots('none') %}
```

I had forgotten about some of the changes the plugin makes depending on the environment when looking at the output HTML, but it is documented in the [docs on the multi-environment config settings](https://nystudio107.com/docs/seomatic/configuring.html#multi-environment-config-settings).

> In local dev and staging environments, the following things change: … `<meta name="robots">` tags are rendered with `none` to prevent Google from indexing the pages …

> SEOmatic also automatically sets the `robots` tag to `none` for everything but the `live` production environment.
