### ISSUE TITLE
Allow custom schema type

### ISSUE THREAD

**Issue by mortscode** [khalwat/seomatic#408]
### Is your feature request related to a problem? Please describe.
I see in the docs that in order to use `seomatic.jsonLd.create()` the type must "be any of the Schema.org types". I have a situation where I need to make a schema block for a type that is not in the Schema.org type list.

Docs ref: https://nystudio107.com/docs/seomatic/using/json-ld-meta.html#json-ld-meta-object-functions

### Describe the solution you would like
Either 
1. a conditional in the `jsonLd.create()` method that allows me to use a custom type
2. a way to make a custom json+ld block that sits beside my main entity (i suppose i could just hard-code one)

### Describe alternatives you have considered
None

**Comment by khalwat** [comment]
This is very unlikely to happen; there probably is no point in creating a schema that isn't a type listed on Schema.org, because then no one has the vocabulary to consume it.

Who are you creating the schema.org info for, if no one can consume it? Is it something you're using internally in some way?
