### ISSUE TITLE
Entry title

### ISSUE THREAD

**Issue by alanski66** [khalwat/seomatic#56]
Is having  {% hook 'seomaticRender' %} in the base template sufficient to render an entry's title or is there further configuration -setup required?
I have installed and configured core settings but the only title for an entry that is shown is the global site title. It is difficult to know what seomatic is intended to do in this context.

**Comment by khalwat** [comment]
Further configuration is required.  Please see the docs under the "SEO Field Meta" and "Dynamic Twig Meta" sections.

**Comment by wfendler** [comment]
I think I may have a similar problem here except entry title isn't being respected on just _one_ of my singles. Looks like my other singles are set up the exact same way but only one isn't working - it's defaulting back to my site SEO settings instead of the entry's.

Also, looks like "SEO Field Meta" is no longer a page in the Wiki docs on here. Is there a new spot you could point me to to troubleshoot this?

**Comment by khalwat** [comment]
It's still a page in the wiki docs:

https://github.com/nystudio107/seomatic/wiki/05.-SEO-Entry-Meta

If you've added an SEOmatic FieldType to your single, and set the title to pull from another field, I'd suggest re-saving the section as per the link above:

> If you add an SEOmatic FieldType to an existing Section that already has entries in it, you'll need to re-save the Section to populate the newly added SEOmatic FieldType with data. You can do this via Settings → Edit My Section → hit Save.
