### ISSUE TITLE
Environment Dependent robots.txt

### ISSUE THREAD

**Issue by noahread** [khalwat/seomatic#58]
It would be great to be able to do a conditional in the robots.txt depending on environment. For example:

`{% if environment = "stage" %}
Disallow: /
{% else %}
Disallow: /craft/
{% endif %}
`

**Comment by khalwat** [comment]
You can do this!  `robots.txt` is a full-fledged Craft template, so you can do whatever you like.

There was a bug that could prevent it from parsing things properly, however, which I've fixed in the current develop branch:

https://github.com/nystudio107/seomatic/tree/develop

I'll do it as an official release after I fix a few more things.
