### ISSUE TITLE
Localize the plugin?

### ISSUE THREAD

**Issue by FrancisBou** [khalwat/seomatic#60]
How would someone translate this plugin in another language?
I have a french speaking client and we would love to use this plugin.
We could provide the translation and make a pull request but I don't know
enough about Craft plugin developpement to start this on my own.

Thank you for your input!

**Comment by khalwat** [comment]
There's a partial Dutch translation in `seomatic/translations` that gives you some idea of how it works.

You can also look at all of the `.twig` files in the `seomatic/templates` folder, anything you see that has a `| t` next to it is something that can be translated.

It'd be great if you were willing to do this, because then I could also find other things that still need translation.

**Comment by FrancisBou** [comment]
Do you know of any way to extract the strings from the plugin and translate them in a .po editor, then convert them back to a PHP array?

**Comment by khalwat** [comment]
I don't, sorry.  There might be such a tool out there, I'm just not aware of it.
