### ISSUE TITLE
Blank string when pulling in field.seoDescription from a field

### ISSUE THREAD

**Issue by benwilkins** [khalwat/seomatic#80]
I have a search results page, and I want to show a summary of the results. Since the results come from multiple sections, all of which have different field sets, I thought the best way to show the summary would be to grab it from the `seomaticMeta.seoDescription` value. When that value is set to pull from another field in the entry, it just returns a blank string. When it's set with Custom Text, it returns the text.

**Comment by khalwat** [comment]
So basically, there's some magic going on behind the scenes when an entry is loaded into a template that makes this work.  I'll have to see if there's a way to hook in so that we can apply this magic when entries are loaded in via craft.entries()

**Comment by khalwat** [comment]
Just checked into `develop`: 
- [Improved] Contents of SEOmatic Meta FieldTypes are now parsed when they are saved, rather than at runtime, which should be faster, and also makes the contents of the fields always accessible.  Please re-save your Sections that use SEOmatic FieldTypes as per: [https://github.com/nystudio107/seomatic/wiki/05.-SEO-Entry-Meta](https://github.com/nystudio107/seomatic/wiki/05.-SEO-Entry-Meta)

https://github.com/nystudio107/seomatic/tree/develop
